version: "3.8"
services:
    web:
        image: php:8.2-apache
        ports:
            - "8080:80"
        volumes:
            - ./html:/var/www/html
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password123456
            MYSQL_DATABASE: blogui
            MYSQL_USER: jose_galdamez
            MYSQL_PASSWORD: password123456
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
